controller:
  image:
    registry: 996452548190.dkr.ecr.us-east-1.amazonaws.com
    image: controller
    tag: v0.47.0

  containerName: nginx-controller

  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  # Configures the ports the nginx-controller listens on
  containerPort:
    http: 80
    https: 443

kind: deployment
